version: '3'
volumes:
  caddy:

services:
  caddy:
    image: caddy:2-alpine
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./caddy:/etc/caddy/
      - ./static:/var/www
    depends_on:
      - "p2p_chat"
      - "red_tetris"
      - "netdata"
    environment:
      # ACME_AGREE: 'true'

  netdata:
    restart: always
    # hostname: netdata.localhost
    image: netdata/netdata
    cap_add:
      - SYS_PTRACE
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro

  # p2p_chat port: 8088
  p2p_chat:
    build: ./p2p_chat

  # red tetris port: 8080
  red_tetris:
    build: ./red_tetris

# networks:
  # internal
